import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [apple, setApple] = useState(false)

  const pay = () => {
    var applePaySession = new ApplePaySession(6, {
      countryCode: "AE",
      currencyCode: "AED",
      supportNetworks: ["visa", "master", "amex", "discover"],
      merchantCapabilities: ["support3DS"],
      total: { label: "Leem", amount: "10.00" }
    })
    applePaySession.begin()
  }

  const MECHAT_ID = "merchant.com.dev.leem";
  const BACKEND_URL_VALIDATE_SESSION = "";
  const BACKEND_URL_PAY = "";

  useEffect(() => {
    if (window.ApplePaySession && ApplePaySession.canMakePaymentsWithActiveCard(MECHAT_ID)) {
      setApple(true)

    }
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js"></script>


      </Head>
      <main className={styles.main}>
        {
          apple && (
            <button onClick={pay}>Pay</button>
          )
        }

      </main>
    </>
  )
}
